# Generated by Django 4.2.28 on 2026-03-02 20:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name="Ім'я")),
                ('last_name', models.CharField(max_length=100, verbose_name='Прізвище')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Автор',
                'verbose_name_plural': 'Автори',
                'ordering': ['first_name', 'last_name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Назва категорії')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
            },
        ),
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Назва книги')),
                ('slug', models.SlugField(unique=True)),
                ('ISBN', models.CharField(max_length=17, verbose_name='ISBN')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.0)], verbose_name='Ціна')),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стара ціна')),
                ('description', models.TextField(verbose_name='Опис')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Кількість')),
                ('image_url', models.URLField(default='https://dummyimage.com/450x300/dee2e6/6c757d.jpg', verbose_name='Зображення')),
                ('authors', models.ManyToManyField(related_name='books', to='books.authormodel', verbose_name='Автори')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.categorymodel', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['title', 'price'],
            },
        ),
    ]
