# Generated by Django 4.2.28 on 2026-02-24 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmodel',
            old_name='category',
            new_name='category_id',
        ),
    ]
