# Generated by Django 4.2.28 on 2026-02-24 19:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_rename_category_bookmodel_category_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmodel',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.categorymodel', verbose_name='Категорія'),
        ),
    ]
