# Generated by Django 4.2.28 on 2026-04-16 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Замовлений товар', 'verbose_name_plural': 'Замовлений товар'},
        ),
    ]
